apiVersion: v1
kind: ReplicationController
metadata:
  name: goapi5
spec:
  replicas: 1
  selector:
    app: goapi
  template:
    metadata:
      name: goapi
      labels:
        app: goapi
    spec:
      containers:
      - name: web-server
        image: sannidocker/myfirstrepository:myimagev1.0
        ports:
        - containerPort: 80
