apiVersion: v1
kind: ReplicationController
metadata:
  name: goapi
spec:
  replicas: 3
  selector:
    app: goapi
  template:
    metadata:
      name: goapi
      labels:
        app: goapi
    spec:
      containers:
      - name: web-server
        image: myimage:v1.0
        ports:
        - containerPort: 80
